from typing import Any, Iterable, Iterator

from torchmlx import Tensor
from . import functional as functional

class Module:
    training: bool
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def forward(self, *args: Any, **kwargs: Any) -> Any: ...
    def parameters(self) -> Iterator[Tensor]: ...
    def to(self, *args: Any, **kwargs: Any) -> Module: ...
    def train(self, mode: bool = True) -> Module: ...
    def eval(self) -> Module: ...
    def register_buffer(self, name: str, tensor: Tensor, persistent: bool = True) -> None: ...

def Parameter(data: Tensor | None = None, requires_grad: bool = True) -> Tensor: ...

class Linear(Module):
    weight: Tensor
    bias: Tensor | None
    def __init__(self, in_features: int, out_features: int, bias: bool = True, device: Any = None, dtype: Any = None) -> None: ...

class Embedding(Module):
    weight: Tensor
    def __init__(self, num_embeddings: int, embedding_dim: int, padding_idx: int | None = None, max_norm: float | None = None, norm_type: float = 2.0, scale_grad_by_freq: bool = False, sparse: bool = False, device: Any = None, dtype: Any = None) -> None: ...

class LayerNorm(Module):
    def __init__(self, normalized_shape: int | Iterable[int], eps: float = 1e-5, elementwise_affine: bool = True, bias: bool = True, device: Any = None, dtype: Any = None) -> None: ...

class Sequential(Module):
    def __init__(self, *args: Module) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int | str) -> Module: ...

class GELU(Module):
    def __init__(self, approximate: str = "none") -> None: ...

class Dropout(Module):
    def __init__(self, p: float = 0.5, inplace: bool = False) -> None: ...

class ModuleList(Module):
    def __init__(self, modules: Iterable[Module] | None = None) -> None: ...
    def __getitem__(self, index: int) -> Module: ...
    def __setitem__(self, index: int, module: Module) -> None: ...
    def __delitem__(self, index: int) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Module]: ...
    def insert(self, index: int, module: Module) -> None: ...
