from typing import Any, Iterable, Sequence

from . import nn as nn, optim as optim

class device:
    type: str
    index: int | None
    def __init__(self, value: str | device) -> None: ...

class Tensor:
    shape: tuple[int, ...]
    ndim: int
    dtype: Any
    device: device
    grad: Any
    def size(self, dim: int | None = None) -> Any: ...
    def view(self, *shape: Any) -> Tensor: ...
    def reshape(self, *shape: Any) -> Tensor: ...
    def transpose(self, dim0: int, dim1: int) -> Tensor: ...
    def unsqueeze(self, dim: int) -> Tensor: ...
    def squeeze(self, dim: int | None = None) -> Tensor: ...
    def flatten(self, start_dim: int = 0, end_dim: int = -1) -> Tensor: ...
    def float(self) -> Tensor: ...
    def bool(self) -> Tensor: ...
    def pow(self, exponent: Any) -> Tensor: ...
    def mean(self, dim: Any = None, keepdim: bool = False, dtype: Any = None) -> Tensor: ...
    def var(self, dim: Any = None, unbiased: bool = True, keepdim: bool = False, *, correction: int | None = None) -> Tensor: ...
    def chunk(self, chunks: int, dim: int = 0) -> tuple[Tensor, ...]: ...
    def to(self, *args: Any, dtype: Any = None, device: Any = None, **kwargs: Any) -> Tensor: ...
    def repeat_interleave(self, repeats: int, dim: int | None = None) -> Tensor: ...
    def masked_fill(self, mask: Tensor, value: Any) -> Tensor: ...
    def expand(self, *sizes: Any) -> Tensor: ...
    def any(self, dim: Any = None, keepdim: bool = False) -> Tensor: ...
    def contiguous(self, memory_format: Any = None) -> Tensor: ...
    def requires_grad_(self, requires_grad: bool = True) -> Tensor: ...
    def backward(self) -> None: ...
    def register_hook(self, hook: Any) -> Any: ...
    def item(self) -> Any: ...
    def __getitem__(self, key: Any) -> Tensor: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __add__(self, other: Any) -> Tensor: ...
    def __radd__(self, other: Any) -> Tensor: ...
    def __sub__(self, other: Any) -> Tensor: ...
    def __rsub__(self, other: Any) -> Tensor: ...
    def __mul__(self, other: Any) -> Tensor: ...
    def __rmul__(self, other: Any) -> Tensor: ...
    def __truediv__(self, other: Any) -> Tensor: ...
    def __rtruediv__(self, other: Any) -> Tensor: ...
    def __pow__(self, other: Any) -> Tensor: ...
    def __matmul__(self, other: Any) -> Tensor: ...
    def __eq__(self, other: object) -> Tensor: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    def __ne__(self, other: object) -> Tensor: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    def __lt__(self, other: Any) -> Tensor: ...
    def __le__(self, other: Any) -> Tensor: ...
    def __gt__(self, other: Any) -> Tensor: ...
    def __ge__(self, other: Any) -> Tensor: ...

float16: Any
float32: Any
float64: Any
bfloat16: Any
int8: Any
int16: Any
int32: Any
int64: Any
uint8: Any
half: Any
double: Any
long: Any
pi: float
backends: Any
cuda: Any

def tensor(data: Any, dtype: Any = None, device: Any = None, requires_grad: bool = False, pin_memory: bool = False) -> Tensor: ...
def from_numpy(array: Any) -> Tensor: ...
def arange(start: Any, end: Any = None, step: Any = 1, *, dtype: Any = None, device: Any = None) -> Tensor: ...
def randint(low: int, high: int, size: Sequence[int], *, dtype: Any = None, device: Any = None, requires_grad: bool = False) -> Tensor: ...
def zeros(*size: Any, dtype: Any = None, device: Any = None, requires_grad: bool = False) -> Tensor: ...
def ones(*size: Any, dtype: Any = None, device: Any = None, requires_grad: bool = False) -> Tensor: ...
def zeros_like(input: Tensor, *, dtype: Any = None, device: Any = None, requires_grad: bool = False) -> Tensor: ...
def ones_like(input: Tensor, *, dtype: Any = None, device: Any = None, requires_grad: bool = False) -> Tensor: ...
def cat(tensors: Iterable[Tensor], dim: int = 0) -> Tensor: ...
def chunk(input: Tensor, chunks: int, dim: int = 0) -> tuple[Tensor, ...]: ...
def transpose(input: Tensor, dim0: int, dim1: int) -> Tensor: ...
def softmax(input: Tensor, dim: int, dtype: Any = None) -> Tensor: ...
def triu(input: Tensor, diagonal: int = 0) -> Tensor: ...
def tril(input: Tensor, diagonal: int = 0) -> Tensor: ...
def topk(input: Tensor, k: int, dim: int | None = None, largest: bool = True, sorted: bool = True) -> tuple[Tensor, Tensor]: ...
def unique(input: Tensor, sorted: bool = True, return_inverse: bool = False, return_counts: bool = False, dim: int | None = None) -> Tensor: ...
def exp(input: Tensor) -> Tensor: ...
def sin(input: Tensor) -> Tensor: ...
def cos(input: Tensor) -> Tensor: ...
def tanh(input: Tensor) -> Tensor: ...
def sqrt(input: Tensor) -> Tensor: ...
def matmul(input: Tensor, other: Tensor) -> Tensor: ...
def outer(input: Tensor, other: Tensor) -> Tensor: ...
def pow(input: Tensor, exponent: Any) -> Tensor: ...
def polar(abs: Tensor, angle: Tensor) -> Tensor: ...
def categorical(logits: Tensor, dim: int = -1, num_samples: int = 1) -> Tensor: ...
def __getattr__(name: str) -> Any: ...
