from typing import Any, Iterable
from torchmlx import Tensor

class AdamW:
    state: Any
    def __init__(self, params: Iterable[Tensor], lr: float = 1e-3, betas: tuple[float, float] = (0.9, 0.999), eps: float = 1e-8, weight_decay: float = 1e-2, amsgrad: bool = False, maximize: bool = False, foreach: bool | None = None, capturable: bool = False, differentiable: bool = False, fused: bool | None = None) -> None: ...
    def zero_grad(self, *args: Any, **kwargs: Any) -> None: ...
    def step(self, *args: Any, **kwargs: Any) -> None: ...
